import './globals.css'
import { Inter } from 'next/font/google'
import Layout from "@/app/components/Layout";
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
        {/* Add Bootstrap CDN links */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"/>

        {/* You can also add any other meta tags or external links you need */}
      </Head>  <body className={inter.className}>
       <header>

          <Layout />
        </header>
       <main>{children}</main>


      </body>
    </html>
  )
}
