import './globals.css';
import { Inter } from 'next/font/google';
import Layout from "@/app/components/Layout";
import 'bootstrap/dist/css/bootstrap.css'
// own css files here
// import "../css/customcss.css";
import Head from "next/head";
import { CartProvider } from "@/app/store/CartContext";
import Footer from "@/app/pages/Footer";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {


    return (
        <html lang="en">

            <body>
                <CartProvider>
                    <header>
                        <Layout />
                    </header>
                    <main>
                        {children}
                        <Footer/>
                    </main>
                </CartProvider>
            </body>
        </html>
    );
}
